using System;
using System.IO;
using System.Threading;
using System.Threading.Tasks;
using EVA.Infrastructure;

var root = Path.Combine(Path.GetTempPath(), "eva-debug-" + Guid.NewGuid().ToString("N"));
Directory.CreateDirectory(root);
var dest = Path.Combine(root, "archives");
Directory.CreateDirectory(dest);
await File.WriteAllTextAsync(Path.Combine(root, "a.txt"), "alpha");
var scanner = new SourceScanner(root, new LocalScanStateIndex(root), excludedPaths: new[] { dest });
var orch = new BackupOrchestrator(root, dest, null, "Password123!", scanner: scanner, writer: new ArchiveWriter());
var r = await orch.RunOnceAsync(DateTimeOffset.UtcNow, false, CancellationToken.None);
Console.WriteLine($"Created={r.CreatedArchive}");
Console.WriteLine($"Success={r.Success}");
Console.WriteLine($"Type={r.ArchiveType}");
Console.WriteLine($"Error={r.Error ?? "<none>"}");
Console.WriteLine($"ArcPath={r.ArchivePath ?? "<none>"}");
Console.WriteLine("Files in dest:");
foreach (var f in Directory.GetFiles(dest)) Console.WriteLine(f);
